NAME	  = libs
SRCS   	 += $(shell find src/ -name "*.c")
SRCS     += $(shell find src/ -name "*.S")

INC_PATH += $(TJUTCORE_HOME)/tests/libs/src
INC_PATH += $(TJUTCORE_HOME)/tests/libs/include

include $(TJUTCORE_HOME)/scripts/compile.mk
