# Makefile for AbstractMachine Kernels and Libraries
# RISC-V 32E Tianjin University of Technology Processor Core

###############################################################################
# 1. Configuration and Architecture Setup
###############################################################################

# Target architecture
ARCH := riscv32e-tpc

# Default target is 'image'
ifeq ($(MAKECMDGOALS),)
  MAKECMDGOALS  = image
  .DEFAULT_GOAL = image
endif

# Override checks for non-build targets (clean, clean-all, html)
ifeq ($(findstring $(MAKECMDGOALS),clean|clean-all|html),)

# Print build information
$(info # Building $(NAME)-$(MAKECMDGOALS) [$(ARCH)])

# Extract ISA and platform from ARCH
ARCH_SPLIT = $(subst -, ,$(ARCH))
ISA        = $(word 1,$(ARCH_SPLIT))
PLATFORM   = $(word 2,$(ARCH_SPLIT))

# Validate that there are source files to build
ifeq ($(flavor SRCS), undefined)
  $(error Nothing to build - SRCS variable is not defined)
endif

# End of build-time checks
endif

## 2. General compilation Targets

### Create the  directory (`build/$ARCH`)
WORK_DIR  = $(shell pwd)
DST_DIR   = $(WORK_DIR)/build/$(ARCH)
$(shell mkdir -p $(DST_DIR))

### Compilation targets (a binary image or archive)
IMAGE_REL = build/$(NAME)-$(ARCH)
IMAGE     = $(abspath $(IMAGE_REL))
ARCHIVE   = $(WORK_DIR)/build/$(NAME)-$(ARCH).a

### Collect the files to be linked: object files (`.o`) and libraries (`.a)
OBJS      = $(addprefix $(DST_DIR)/, $(addsuffix .o, $(basename $(SRCS))))
LIBS  	 := $(TJUTCORE_HOME)/tests/libs
LINKAGE   = $(OBJS) \
			$(LIBS)/build/libs-$(ARCH).a


## 3. General Compilation Flags

### (Cross) compilers
AS        		= $(CROSS_COMPILE)gcc
CC        		= $(CROSS_COMPILE)gcc
CXX       		= $(CROSS_COMPILE)g++
LD        		= $(CROSS_COMPILE)ld
AR        		= $(CROSS_COMPILE)ar
OBJDUMP   		= $(CROSS_COMPILE)objdump
OBJCOPY   		= $(CROSS_COMPILE)objcopy
READELF   		= $(CROSS_COMPILE)readelf

### Compilation flags
CROSS_COMPILE  := riscv64-linux-gnu-
COMMON_CFLAGS  := -fno-pic -march=rv32e_zicsr -mabi=ilp32e \
				  -mcmodel=medany -mstrict-align 

INCFLAGS       := -I$(TJUTCORE_HOME)/tests/libs/include \
				  -I$(WORK_DIR)/include 

CFLAGS		   += $(COMMON_CFLAGS) $(INCFLAGS) -static \
				  -O2 -MMD -Wall -Werror -Wno-main \
				  -fdata-sections -ffunction-sections \
				  -DMAINARGS=\"$(mainargs)\" \
				  -fno-asynchronous-unwind-tables \
				  -fno-builtin -fno-stack-protector 

CXXFLAGS  	   += $(CFLAGS) -ffreestanding -fno-rtti -fno-exceptions

ASFLAGS 	   += $(COMMON_CFLAGS) $(INCFLAGS) -O0 -MMD \
				  
LDFLAGS 	   += -melf32lriscv -T $(TJUTCORE_HOME)/scripts/linker.ld \
				  --defsym=_pmem_start=0x0 \
				  --defsym=_entry_offset=0x0 \
				  -z noexecstack

## 4. Compilation Rules

### Rule (compile): a single `.c` -> `.o` (gcc)
$(DST_DIR)/%.o: %.c
	@mkdir -p $(dir $@) && echo + CC $<
	@$(CC) -std=gnu11 $(CFLAGS) -c -o $@ $(realpath $<)

### Rule (compile): a single `.cc` -> `.o` (g++)
$(DST_DIR)/%.o: %.cc
	@mkdir -p $(dir $@) && echo + CXX $<
	@$(CXX) -std=c++17 $(CXXFLAGS) -c -o $@ $(realpath $<)

### Rule (compile): a single `.cpp` -> `.o` (g++)
$(DST_DIR)/%.o: %.cpp
	@mkdir -p $(dir $@) && echo + CXX $<
	@$(CXX) -std=c++17 $(CXXFLAGS) -c -o $@ $(realpath $<)

### Rule (compile): a single `.S` -> `.o` (gcc, which preprocesses and calls as)
$(DST_DIR)/%.o: %.S
	@mkdir -p $(dir $@) && echo + AS $<
	@$(AS) $(ASFLAGS) -c -o $@ $(realpath $<)

### Rule (recursive make): build a dependent library (am, klib, ...)
$(LIBS): %:
	@$(MAKE) -s -C $(TJUTCORE_HOME)/tests/libs ARCH=$(ARCH) archive

### Rule (link): objects (`*.o`) and libraries (`*.a`) -> `IMAGE.elf`, the final ELF binary to be packed into image (ld)
$(IMAGE).elf: $(OBJS) $(LIBS)
	@echo + LD "->" $(IMAGE_REL).elf
	@$(LD) $(LDFLAGS) -o $(IMAGE).elf --start-group $(LINKAGE) --end-group

### Rule (archive): objects (`*.o`) ->" `ARCHIVE.a` (ar)
#### 将.o文件链接生成.a文件
$(ARCHIVE): $(OBJS)
	@echo + AR "->" $(shell realpath $@ --relative-to .)
	@$(AR) rcs $(ARCHIVE) $(OBJS)

image: $(IMAGE).elf
	@$(OBJDUMP) -d $(IMAGE).elf > $(IMAGE).txt
	@echo + OBJCOPY "->" $(IMAGE_REL).bin
	@$(OBJCOPY) -S --set-section-flags .bss=alloc,contents -O binary $(IMAGE).elf $(IMAGE).bin

### Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(addprefix $(DST_DIR)/, $(addsuffix .d, $(basename $(SRCS))))

## 5. Miscellaneous

### Build order control
image: image-dep
archive: $(ARCHIVE)
image-dep: $(OBJS) $(LIBS)
	@echo \# Creating image [$(ARCH)]
.PHONY: image image-dep archive $(LIBS)

### Clean a single project (remove `build/`)
clean:
	rm -rf Makefile.html $(WORK_DIR)/build/
.PHONY: clean

### Clean all sub-projects within depth 2 (and ignore errors)
CLEAN_ALL = $(dir $(shell find . -mindepth 2 -name Makefile))
clean-all: $(CLEAN_ALL) clean
$(CLEAN_ALL):
	-@$(MAKE) -s -C $@ clean
.PHONY: clean-all $(CLEAN_ALL)
